version: "3.9"
services:
  rsync-cron:
    build:
      context: ./.docker
      dockerfile: rs-cron.Dockerfile
    restart: always
    volumes:
        - /mnt/nas/mirror:/mnt/mirror/
    networks:
    - homenetwork
  
  caddy2:
    image: caddy:2.4.3-alpine
    container_name: caddy2-mirror
    cap_add:
      - NET_ADMIN
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Asia/Singapore
    restart: always
    volumes:  
      - ./caddy/caddy:/etc/caddy
      - ./caddy/site:/srv 
      - caddy_data:/data
      - caddy_config:/config
      - /mnt/nas/mirror/pub:/var/www/mirror
    networks:
      - homenetwork
    ports:
    - "9004:80"
    - "9005:443"
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx-mirror.rule=Host(`mirror.jingk.ai`)
      - traefik.http.routers.nginx-mirror.entrypoints=http
      - traefik.http.routers.nginx-mirror.service=nginx-mirror-service
      - traefik.http.services.nginx-mirror-service.loadbalancer.server.port=80

      - "traefik.tcp.routers.nginx-mirrors.rule=HostSNI(`mirror.jingk.ai`)"
      - "traefik.tcp.routers.nginx-mirrors.tls.passthrough=true"
      - "traefik.tcp.services.nginx-mirrors.loadbalancer.server.port=443"

volumes:
  caddy_data:
    external: true
  caddy_config:
networks:
    homenetwork:
        external: true
