version: "3.9"

services:
  rsync-crond:
    build:
      context: ./rsync-alpine
    container_name: rsync-crondaemon
    restart: unless-stopped
    volumes:
      - /mnt/local/raid/mirror:/mirror

  rsyncd:
    build:
      context: ./rsyncd
    container_name: rsyncd
    restart: unless-stopped
    ports:
      - "873:873"
    volumes:
      - /opt/mirror/rsyncd/config:/config
      - /opt/mirror/rsyncd/log:/log
      - /mnt/local/raid/mirror:/mirror

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: unless-stopped
    volumes:
      - /mnt/local/raid/mirror:/usr/share/nginx/html:ro

